name: HabilidadesBedwars
version: '1.2.2-SNAPSHOT'
main: com.theangel099.habilidadesbedwars.HabilidadesBedwarsPlugin
api-version: '1.21'
authors: [TheAngel099]
description: Addon de Habilidades Modernas para Marcely's Bedwars

depend:
  - MBedwars

softdepend:
  - BedwarsCosmetics
  - MBedwarsTweaks
  - PrivateGamesAddon

commands:
  habilidadesbedwars:
    description: Comando principal del plugin de habilidades.
    aliases: [hb, habilidades]
    permission: habilidadesbedwars.admin

