name: HabilidadesBedwars
version: '1.0.0-SNAPSHOT'
main: com.theangel099.habilidadesbedwars.HabilidadesBedwarsPlugin
api-version: '1.21'
authors: [TheAngel099]
description: Addon de Habilidades Modernas para Marcely's Bedwars

depend:
  - MBedwars

softdepend:
  - MBedwars-Cosmetics
  - MBedwarsTweaks
  - PrivateGamesAddon

